POST  http://127.0.0.1:8000/oauth/token
Accept: application/json
Content-Type: application/json

{
    "grant_type" : "password",
    "client_id" : "2",
    "client_secret" : "QV10hLwh3xRc7CxgvpDKstG009VyzUDV6A3kzHcB",
    "username" : "tester@gmail.com",
    "password" : "123456"
}

