POST  http://127.0.0.1:8000/oauth/token
Accept: application/json
Content-Type: application/json

{
    "grant_type" : "password",
    "client_id" : "2",
    "client_secret" : "bGoe3eY7CWJMOLCqgXTrtUJVNig7fxvNQymWiLji",
    "username" : "wrosenbaum@example.com",
    "password" : "password"
}

